# GLOBAL variables: which can be consumed by all charts
# images, contrail_env, contrail_env_vrouter_dpdk, contrail_env_vrouter_kernel
global:
  # section to configure images for all containers
  images:
    tags:
      # You can override container names here using container name as a tag. Just replace '-' in container name to '_'. See example:
      #   contrail_external_kafka: "docker.io/opencontrailnightly/contrail-external-kafka:master-latest"
      dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    imagePullPolicy: "IfNotPresent"
    # Specify imageCredentials
    imageCredentials:
      # registry: quay.io
      # username: username
      # password: password


  # contrail_env section for all containers
  contrail_env:
    CONTROLLER_NODES: 6.6.6.6
    LOG_LEVEL: SYS_NOTICE
    CLOUD_ORCHESTRATOR: openstack
    AAA_MODE: cloud-admin
    ANALYTICSDB_ENABLE: "true"
    ANALYTICS_ALARM_ENABLE: "true"
    ANALYTICS_SNMP_ENABLE: "true"
  # Values from this section will be passed as ENV variables to all provisioner containers
  default_env:
  #  VXLAN_VN_ID_MODE: "automatic"
  # section of vrouter template for kernel mode
  contrail_env_vrouter_kernel:
    AGENT_MODE: kernel

  # section of vrouter template for dpdk mode
  contrail_env_vrouter_dpdk:
    AGENT_MODE: dpdk
    #CPU_CORE_MASK: "0xf"
    #DPDK_UIO_DRIVER: uio_pci_generic
    #HUGE_PAGES: 32000
    #HUGE_PAGES_DIR: /dev/hugepages
    #DPDK_MEM_PER_SOCKET: 1024

  node:
    host_os: ubuntu

# Chart level variables like manifests, labels which are local to subchart
# Can be updated from the parent chart like below
# Example of overriding values of subchart, where contrail-vrouter is name of the subchart
contrail-vrouter:
  manifests:
    configmap_vrouter_dpdk: false
    daemonset_dpdk: false

# Example for configuring nginx ingress controller
contrail-controller:
  # Ingress related inputs are defined here
  ingress:
    config_api:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
      - name: contrail-config-api
        path: /
      - name: contrail-config-api.contrail
        path: /
      - name: contrail-config-api.contrail.svc.cluster.local
        path: /

    webui:
      annotations:
        kubernetes.io/ingress.class: nginx-cluster
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/rewrite-target: /
        # tls will be terminated at the pod
        nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        # session affinity related annotations
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/session-cookie-hash: sha1
        nginx.ingress.kubernetes.io/session-cookie-name: route
      hosts:
      - name: contrail-webui
        path: /
      - name: contrail-webui.contrail
        path: /
      - name: contrail-webui.contrail.svc.cluster.local
        path: /

  manifests:
    ingress_webui: true
    ingress_config_api: true

contrail-analytics:
  ingress:
    analytics_api:
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
      hosts:
        - name: contrail-analytics-api
          path: /
        - name: contrail-analytics-api.contrail
          path: /
        - name: contrail-analytics-api.contrail.svc.cluster.local
          path: /

  manifests:
    ingress_analytics_api: true
