apiVersion: v1
name: contrail-analytics
description: Helm chart for Contrail Analytics
version: 0.1.0
appVersion: Contrail 5.0.0
home: https://github.com/opensdn-io/tf-helm-deployer/
sources:
  - https://github.com/opensdn-io/tf-controller/
tillerVersion: ">=2.4.0"
keywords:
  - Contrail
  - SDN
